<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>GameRes.Net20</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Configurations>Debug;Prerelease;Release</Configurations>
    <AssemblyTitle>Net20</AssemblyTitle>
    <Description>.NET 2.0 dependent classes</Description>
    <Company>mørkt</Company>
    <Product>Net20</Product>
    <Copyright>Copyright © 2018 mørkt</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\bin\Debug\</OutputPath>
    <BaseAddress>301989888</BaseAddress>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\bin\Release\</OutputPath>
    <DefineConstants>
    </DefineConstants>
    <BaseAddress>301989888</BaseAddress>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Prerelease|AnyCPU'">
    <OutputPath>..\bin\Prerelease\</OutputPath>
    <Optimize>true</Optimize>
    <BaseAddress>301989888</BaseAddress>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" PrivateAssets="all" Version="1.0.3" />
  </ItemGroup>
</Project>