//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameRes.Formats.Strings {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class arcStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal arcStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameRes.Formats.Strings.arcStrings", typeof(arcStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Archive contents might be encrypted,
        ///choose appropriate encryption scheme..
        /// </summary>
        public static string AGSMightBeEncrypted {
            get {
                return ResourceManager.GetString("AGSMightBeEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Base archive.
        /// </summary>
        public static string AMIBaseArchive {
            get {
                return ResourceManager.GetString("AMIBaseArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New archive will also contain entries from the base archive..
        /// </summary>
        public static string AMIBaseTooltip {
            get {
                return ResourceManager.GetString("AMIBaseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select base archive.
        /// </summary>
        public static string AMIChooseBase {
            get {
                return ResourceManager.GetString("AMIChooseBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amaterasu Translations Muv-Luv archive.
        /// </summary>
        public static string AMIDescription {
            get {
                return ResourceManager.GetString("AMIDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No files suitable for AMI archive found..
        /// </summary>
        public static string AMINoFiles {
            get {
                return ResourceManager.GetString("AMINoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default.
        /// </summary>
        public static string ArcDefault {
            get {
                return ResourceManager.GetString("ArcDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Archive content is encrypted.
        ///Choose appropriate encryption scheme..
        /// </summary>
        public static string ArcEncryptedNotice {
            get {
                return ResourceManager.GetString("ArcEncryptedNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 32-bit hex number.
        /// </summary>
        public static string ArcHex32Bit {
            get {
                return ResourceManager.GetString("ArcHex32Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ignore encryption.
        /// </summary>
        public static string ArcIgnoreEncryption {
            get {
                return ResourceManager.GetString("ArcIgnoreEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image is encrypted..
        /// </summary>
        public static string ArcImageEncrypted {
            get {
                return ResourceManager.GetString("ArcImageEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на no encryption.
        /// </summary>
        public static string ArcNoEncryption {
            get {
                return ResourceManager.GetString("ArcNoEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset.
        /// </summary>
        public static string ArcReset {
            get {
                return ResourceManager.GetString("ArcReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose title or enter a password.
        /// </summary>
        public static string ArcTitleOrPassword {
            get {
                return ResourceManager.GetString("ArcTitleOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default file names encoding.
        /// </summary>
        public static string DefaultEncoding {
            get {
                return ResourceManager.GetString("DefaultEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Encryption keys.
        /// </summary>
        public static string DPKKeys {
            get {
                return ResourceManager.GetString("DPKKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Archive contains encrypted scripts.
        ///Choose encryption scheme or enter a passphrase..
        /// </summary>
        public static string FJSYSNotice {
            get {
                return ResourceManager.GetString("FJSYSNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose title or enter a key.
        /// </summary>
        public static string GALChoose {
            get {
                return ResourceManager.GetString("GALChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на âge proprietary image format.
        /// </summary>
        public static string GRPDescription {
            get {
                return ResourceManager.GetString("GRPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Liar-soft proprietary script format.
        /// </summary>
        public static string GSCDescription {
            get {
                return ResourceManager.GetString("GSCDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image is encrypted.
        ///Choose appropriate encryption scheme..
        /// </summary>
        public static string GYUImageEncrypted {
            get {
                return ResourceManager.GetString("GYUImageEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose game executable file.
        /// </summary>
        public static string INTChooseExe {
            get {
                return ResourceManager.GetString("INTChooseExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Encrypted archives creation is not implemented..
        /// </summary>
        public static string INTCreationNotice {
            get {
                return ResourceManager.GetString("INTCreationNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CatSystem2 engine resource archive.
        /// </summary>
        public static string INTDescription {
            get {
                return ResourceManager.GetString("INTDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check EXE.
        /// </summary>
        public static string INTExeButton {
            get {
                return ResourceManager.GetString("INTExeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Executable Files.
        /// </summary>
        public static string INTExeFiles {
            get {
                return ResourceManager.GetString("INTExeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key not found within {0}..
        /// </summary>
        public static string INTKeyNotFound {
            get {
                return ResourceManager.GetString("INTKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Numeric key should be a 32-bit hexadecimal integer.
        /// </summary>
        public static string INTKeyRequirement {
            get {
                return ResourceManager.GetString("INTKeyRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Numeric key.
        /// </summary>
        public static string INTLabelNumericKey {
            get {
                return ResourceManager.GetString("INTLabelNumericKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press &quot;Check EXE&quot; button to look for key within game executable file..
        /// </summary>
        public static string INTMessage1 {
            get {
                return ResourceManager.GetString("INTMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alternatively, enter archive encryption key or choose one of the predefined encryption schemes..
        /// </summary>
        public static string INTMessage2 {
            get {
                return ResourceManager.GetString("INTMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Archive directory is encrypted..
        /// </summary>
        public static string INTNotice {
            get {
                return ResourceManager.GetString("INTNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default.
        /// </summary>
        public static string KCAPDefault {
            get {
                return ResourceManager.GetString("KCAPDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kogado game engine resource archive.
        /// </summary>
        public static string KogadoDescription {
            get {
                return ResourceManager.GetString("KogadoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Encryption scheme.
        /// </summary>
        public static string LabelEncScheme {
            get {
                return ResourceManager.GetString("LabelEncScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passphrase.
        /// </summary>
        public static string LabelPassphrase {
            get {
                return ResourceManager.GetString("LabelPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scheme.
        /// </summary>
        public static string LabelScheme {
            get {
                return ResourceManager.GetString("LabelScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Liar-soft image archive.
        /// </summary>
        public static string LWGDescription {
            get {
                return ResourceManager.GetString("LWGDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Archive contains encrypted scripts.
        ///Choose encryption scheme or enter a passphrase..
        /// </summary>
        public static string MBLNotice {
            get {
                return ResourceManager.GetString("MBLNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Archive content is encrypted..
        /// </summary>
        public static string MCAEncryptedNotice {
            get {
                return ResourceManager.GetString("MCAEncryptedNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose title or enter a key.
        /// </summary>
        public static string MCGChoose {
            get {
                return ResourceManager.GetString("MCGChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8-bit encryption key.
        /// </summary>
        public static string MCGLabelKey {
            get {
                return ResourceManager.GetString("MCGLabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adding file.
        /// </summary>
        public static string MsgAddingFile {
            get {
                return ResourceManager.GetString("MsgAddingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculating checksum....
        /// </summary>
        public static string MsgCalculatingChecksum {
            get {
                return ResourceManager.GetString("MsgCalculatingChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compressing index....
        /// </summary>
        public static string MsgCompressingIndex {
            get {
                return ResourceManager.GetString("MsgCompressingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Encryption key required for archive creation..
        /// </summary>
        public static string MsgCreationKeyRequired {
            get {
                return ResourceManager.GetString("MsgCreationKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Encryption method not implemented.
        /// </summary>
        public static string MsgEncNotImplemented {
            get {
                return ResourceManager.GetString("MsgEncNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File name extension too long..
        /// </summary>
        public static string MsgExtensionTooLong {
            get {
                return ResourceManager.GetString("MsgExtensionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File name is too long.
        /// </summary>
        public static string MsgFileNameTooLong {
            get {
                return ResourceManager.GetString("MsgFileNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File name contains illegal characters.
        /// </summary>
        public static string MsgIllegalCharacters {
            get {
                return ResourceManager.GetString("MsgIllegalCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: image format not recognized..
        /// </summary>
        public static string MsgInvalidImageFormat {
            get {
                return ResourceManager.GetString("MsgInvalidImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid archive version specified..
        /// </summary>
        public static string MsgInvalidVersion {
            get {
                return ResourceManager.GetString("MsgInvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File name without extension..
        /// </summary>
        public static string MsgNoExtension {
            get {
                return ResourceManager.GetString("MsgNoExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of files exceedes archive limit..
        /// </summary>
        public static string MsgTooManyFiles {
            get {
                return ResourceManager.GetString("MsgTooManyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Updating index....
        /// </summary>
        public static string MsgUpdatingIndex {
            get {
                return ResourceManager.GetString("MsgUpdatingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Writing index....
        /// </summary>
        public static string MsgWritingIndex {
            get {
                return ResourceManager.GetString("MsgWritingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compress contents.
        /// </summary>
        public static string NPACompressContents {
            get {
                return ResourceManager.GetString("NPACompressContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nitro+ resource archive.
        /// </summary>
        public static string NPADescription {
            get {
                return ResourceManager.GetString("NPADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Encryption keys
        ///(required even if contents is not encrypted).
        /// </summary>
        public static string NPAKeys {
            get {
                return ResourceManager.GetString("NPAKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nitro+ Steins;Gate resource archive.
        /// </summary>
        public static string NPASteinsGateDescription {
            get {
                return ResourceManager.GetString("NPASteinsGateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NScripter game engine resource archive.
        /// </summary>
        public static string NSADescription {
            get {
                return ResourceManager.GetString("NSADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default audio sampling rate.
        /// </summary>
        public static string ODNAudioSampleRate {
            get {
                return ResourceManager.GetString("ODNAudioSampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fix Ogg files checksums.
        /// </summary>
        public static string OGGFixCrc {
            get {
                return ResourceManager.GetString("OGGFixCrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Archive type.
        /// </summary>
        public static string ONSArchiveType {
            get {
                return ResourceManager.GetString("ONSArchiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compression.
        /// </summary>
        public static string ONSCompression {
            get {
                return ResourceManager.GetString("ONSCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на None.
        /// </summary>
        public static string ONSCompressionNone {
            get {
                return ResourceManager.GetString("ONSCompressionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Flying Shine resource archive.
        /// </summary>
        public static string PDDescription {
            get {
                return ResourceManager.GetString("PDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scramble contents.
        /// </summary>
        public static string PDScrambleContents {
            get {
                return ResourceManager.GetString("PDScrambleContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use default encryption scheme.
        /// </summary>
        public static string QLIEDefaultScheme {
            get {
                return ResourceManager.GetString("QLIEDefaultScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load transparency data from RC8 bitmap.
        /// </summary>
        public static string RCTApplyMask {
            get {
                return ResourceManager.GetString("RCTApplyMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatically combine incremental frames.
        /// </summary>
        public static string RCTOverlayFrames {
            get {
                return ResourceManager.GetString("RCTOverlayFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ren&apos;Py game engine archive.
        /// </summary>
        public static string RPADescription {
            get {
                return ResourceManager.GetString("RPADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 32-bit key.
        /// </summary>
        public static string RPALabelKey {
            get {
                return ResourceManager.GetString("RPALabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File resembles RPM resource archive,
        ///but encryption key guess failed.
        ///Choose appropriate encryption scheme..
        /// </summary>
        public static string RPMEncryptedNotice {
            get {
                return ResourceManager.GetString("RPMEncryptedNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amaterasu Translations Muv-Luv script file.
        /// </summary>
        public static string SCRDescription {
            get {
                return ResourceManager.GetString("SCRDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filename encoding.
        /// </summary>
        public static string SGLabelEncoding {
            get {
                return ResourceManager.GetString("SGLabelEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hex number.
        /// </summary>
        public static string TooltipHex {
            get {
                return ResourceManager.GetString("TooltipHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum file name length
        ///(not including extension).
        /// </summary>
        public static string WARCLabelLength {
            get {
                return ResourceManager.GetString("WARCLabelLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Liar-soft game resource archive.
        /// </summary>
        public static string XFLDescription {
            get {
                return ResourceManager.GetString("XFLDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compress contents.
        /// </summary>
        public static string XP3CompressContents {
            get {
                return ResourceManager.GetString("XP3CompressContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compress directory.
        /// </summary>
        public static string XP3CompressHeader {
            get {
                return ResourceManager.GetString("XP3CompressHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KiriKiri game engine resource archive.
        /// </summary>
        public static string XP3Description {
            get {
                return ResourceManager.GetString("XP3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Archive content could be encrypted.
        ///Choose appropriate encryption scheme..
        /// </summary>
        public static string XP3EncryptedNotice {
            get {
                return ResourceManager.GetString("XP3EncryptedNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version.
        /// </summary>
        public static string XP3LabelVersion {
            get {
                return ResourceManager.GetString("XP3LabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retain directory structure.
        /// </summary>
        public static string XP3RetainStructure {
            get {
                return ResourceManager.GetString("XP3RetainStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yu-Ris game engine resource archive.
        /// </summary>
        public static string YPFDescription {
            get {
                return ResourceManager.GetString("YPFDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8-bit encryption key.
        /// </summary>
        public static string YPFLabelKey {
            get {
                return ResourceManager.GetString("YPFLabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Archive version.
        /// </summary>
        public static string YPFLabelVersion {
            get {
                return ResourceManager.GetString("YPFLabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Archive directory is encrypted.
        ///Choose appropriate encryption scheme..
        /// </summary>
        public static string YPFNotice {
            get {
                return ResourceManager.GetString("YPFNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Try to guess.
        /// </summary>
        public static string YPFTryGuess {
            get {
                return ResourceManager.GetString("YPFTryGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Archive content is encrypted..
        /// </summary>
        public static string ZIPEncryptedNotice {
            get {
                return ResourceManager.GetString("ZIPEncryptedNotice", resourceCulture);
            }
        }
    }
}
