<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.1.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <PublishWizardCompleted>true</PublishWizardCompleted>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\</SolutionDir>
    <RestorePackages>true</RestorePackages>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Configurations>Debug;Prerelease;Release</Configurations>
    <ApplicationIcon>Images\sample.ico</ApplicationIcon>
    <ManifestCertificateThumbprint>751F4A9FD4F4CC3D99D70509FF1F9D9CC9E49516</ManifestCertificateThumbprint>
    <!-- <ManifestKeyFile>GARbro.GUI_TemporaryKey.pfx</ManifestKeyFile> -->
    <GenerateManifests>false</GenerateManifests>
    <TargetZone>LocalIntranet</TargetZone>
    <!-- <SignManifests>true</SignManifests> -->
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
    <PreBuildEvent>perl "$(SolutionDir)inc-revision.pl" "$(ProjectPath)" $(ConfigurationName) "$(SolutionDir)\"
exit 0</PreBuildEvent>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\bin\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <OutputPath>..\bin\Release\</OutputPath>
    <DefineConstants>
    </DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Prerelease|AnyCPU'">
    <OutputPath>..\bin\Prerelease\</OutputPath>
    <Optimize>true</Optimize>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="GarUpdate.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="ProgressDialog\ProgressDialog.cs">
      <SubType>Component</SubType>
    </Compile>
    <PackageReference Include="NAudio" Version="1.10.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="WindowsAPICodePack-Core" Version="1.1.2" />
    <PackageReference Include="WindowsAPICodePack-Shell" Version="1.1.1" />
    <PackageReference Include="WPFToolkit" Version="3.5.50211.1" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\LICENSE" />
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\32x32\back button.png" />
    <Resource Include="Images\32x32\forward button.png" />
    <Resource Include="Images\32x32\help.png" />
    <Resource Include="Images\64x64\info.png" />
    <Resource Include="Images\sample.ico" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\48x48\refresh.png" />
    <SplashScreen Include="Images\splashscreen.png" />
    <Resource Include="Images\search4files.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GameRes\GameRes.csproj" />
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include=".NETFramework,Version=v4.5">
      <Visible>False</Visible>
      <ProductName>Microsoft .NET Framework 4.5 %28x86 and x64%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Client.3.5">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1 Client Profile</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Cursors\grab.cur" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Cursors\grabbing.cur" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\64x64\actions.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\64x64\alert.png" />
  </ItemGroup>
</Project>