//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARbro.GUI.Strings {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class guiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal guiStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GARbro.GUI.Strings.guiStrings", typeof(guiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Abort.
        /// </summary>
        public static string ButtonAbort {
            get {
                return ResourceManager.GetString("ButtonAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        public static string ButtonApply {
            get {
                return ResourceManager.GetString("ButtonApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Continue.
        /// </summary>
        public static string ButtonContinue {
            get {
                return ResourceManager.GetString("ButtonContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert.
        /// </summary>
        public static string ButtonConvert {
            get {
                return ResourceManager.GetString("ButtonConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Download.
        /// </summary>
        public static string ButtonDownload {
            get {
                return ResourceManager.GetString("ButtonDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extract.
        /// </summary>
        public static string ButtonExtract {
            get {
                return ResourceManager.GetString("ButtonExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Overwrite.
        /// </summary>
        public static string ButtonOverwrite {
            get {
                return ResourceManager.GetString("ButtonOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Rename.
        /// </summary>
        public static string ButtonRename {
            get {
                return ResourceManager.GetString("ButtonRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Skip.
        /// </summary>
        public static string ButtonSkip {
            get {
                return ResourceManager.GetString("ButtonSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Close.
        /// </summary>
        public static string CtxMenuClose {
            get {
                return ResourceManager.GetString("CtxMenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert multimedia....
        /// </summary>
        public static string CtxMenuConvert {
            get {
                return ResourceManager.GetString("CtxMenuConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy.
        /// </summary>
        public static string CtxMenuCopy {
            get {
                return ResourceManager.GetString("CtxMenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create archive....
        /// </summary>
        public static string CtxMenuCreate {
            get {
                return ResourceManager.GetString("CtxMenuCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cut.
        /// </summary>
        public static string CtxMenuCut {
            get {
                return ResourceManager.GetString("CtxMenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Delete.
        /// </summary>
        public static string CtxMenuDelete {
            get {
                return ResourceManager.GetString("CtxMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browse in _Explorer.
        /// </summary>
        public static string CtxMenuExplorer {
            get {
                return ResourceManager.GetString("CtxMenuExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extract.
        /// </summary>
        public static string CtxMenuExtract {
            get {
                return ResourceManager.GetString("CtxMenuExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assign file type.
        /// </summary>
        public static string CtxMenuFileType {
            get {
                return ResourceManager.GetString("CtxMenuFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        public static string CtxMenuOpen {
            get {
                return ResourceManager.GetString("CtxMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paste.
        /// </summary>
        public static string CtxMenuPaste {
            get {
                return ResourceManager.GetString("CtxMenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh.
        /// </summary>
        public static string CtxMenuRefresh {
            get {
                return ResourceManager.GetString("CtxMenuRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Rename.
        /// </summary>
        public static string CtxMenuRename {
            get {
                return ResourceManager.GetString("CtxMenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select files by mask....
        /// </summary>
        public static string CtxMenuSelectByMask {
            get {
                return ResourceManager.GetString("CtxMenuSelectByMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort by.
        /// </summary>
        public static string CtxMenuSortBy {
            get {
                return ResourceManager.GetString("CtxMenuSortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string CtxMenuSortByName {
            get {
                return ResourceManager.GetString("CtxMenuSortByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size.
        /// </summary>
        public static string CtxMenuSortBySize {
            get {
                return ResourceManager.GetString("CtxMenuSortBySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        public static string CtxMenuSortByType {
            get {
                return ResourceManager.GetString("CtxMenuSortByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unsorted.
        /// </summary>
        public static string CtxMenuUnsorted {
            get {
                return ResourceManager.GetString("CtxMenuUnsorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string HeaderName {
            get {
                return ResourceManager.GetString("HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size.
        /// </summary>
        public static string HeaderSize {
            get {
                return ResourceManager.GetString("HeaderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        public static string HeaderType {
            get {
                return ResourceManager.GetString("HeaderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A_pply to all duplicate files.
        /// </summary>
        public static string LabelApplyToAll {
            get {
                return ResourceManager.GetString("LabelApplyToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Archive format.
        /// </summary>
        public static string LabelArchiveFormat {
            get {
                return ResourceManager.GetString("LabelArchiveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Archive name.
        /// </summary>
        public static string LabelArchiveName {
            get {
                return ResourceManager.GetString("LabelArchiveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Archive options.
        /// </summary>
        public static string LabelArchiveOptions {
            get {
                return ResourceManager.GetString("LabelArchiveOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Destination directory.
        /// </summary>
        public static string LabelDestinationDir {
            get {
                return ResourceManager.GetString("LabelDestinationDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose destination format for images.
        /// </summary>
        public static string LabelDestinationFormat {
            get {
                return ResourceManager.GetString("LabelDestinationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Development site.
        /// </summary>
        public static string LabelDevSite {
            get {
                return ResourceManager.GetString("LabelDevSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What should be done?.
        /// </summary>
        public static string LabelDuplicateFileQuestion {
            get {
                return ResourceManager.GetString("LabelDuplicateFileQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Encoding.
        /// </summary>
        public static string LabelEncoding {
            get {
                return ResourceManager.GetString("LabelEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter wildcard mask.
        /// </summary>
        public static string LabelEnterMask {
            get {
                return ResourceManager.GetString("LabelEnterMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extract files from {0} to.
        /// </summary>
        public static string LabelExtractAllTo {
            get {
                return ResourceManager.GetString("LabelExtractAllTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extract {0} to.
        /// </summary>
        public static string LabelExtractFileTo {
            get {
                return ResourceManager.GetString("LabelExtractFileTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Ignore further errors.
        /// </summary>
        public static string LabelIgnoreErrors {
            get {
                return ResourceManager.GetString("LabelIgnoreErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Release notes.
        /// </summary>
        public static string LabelReleaseNotes {
            get {
                return ResourceManager.GetString("LabelReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Skip incovertible files..
        /// </summary>
        public static string LabelSkipFailures {
            get {
                return ResourceManager.GetString("LabelSkipFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About Game Resource browser.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Check for updates....
        /// </summary>
        public static string MenuCheckUpdates {
            get {
                return ResourceManager.GetString("MenuCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E_xit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fit preview _window to image.
        /// </summary>
        public static string MenuFitWindow {
            get {
                return ResourceManager.GetString("MenuFitWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open....
        /// </summary>
        public static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Preferences.
        /// </summary>
        public static string MenuPreferences {
            get {
                return ResourceManager.GetString("MenuPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recent files.
        /// </summary>
        public static string MenuRecent {
            get {
                return ResourceManager.GetString("MenuRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show/hide main _menu bar.
        /// </summary>
        public static string MenuToggleMenuBar {
            get {
                return ResourceManager.GetString("MenuToggleMenuBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show/hide _status bar.
        /// </summary>
        public static string MenuToggleStatusBar {
            get {
                return ResourceManager.GetString("MenuToggleStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show/hide _toolbar.
        /// </summary>
        public static string MenuToggleToolBar {
            get {
                return ResourceManager.GetString("MenuToggleToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _View.
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose files to extract.
        /// </summary>
        public static string MsgChooseFiles {
            get {
                return ResourceManager.GetString("MsgChooseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to delete these files?.
        /// </summary>
        public static string MsgConfirmDeleteFiles {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Converting file {0}.
        /// </summary>
        public static string MsgConvertingFile {
            get {
                return ResourceManager.GetString("MsgConvertingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creating archive {0}.
        /// </summary>
        public static string MsgCreatingArchive {
            get {
                return ResourceManager.GetString("MsgCreatingArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deleted {0}.
        /// </summary>
        public static string MsgDeletedItem {
            get {
                return ResourceManager.GetString("MsgDeletedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deleted {0} file.
        /// </summary>
        public static string MsgDeletedItems1 {
            get {
                return ResourceManager.GetString("MsgDeletedItems1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deleted {0} files.
        /// </summary>
        public static string MsgDeletedItems2 {
            get {
                return ResourceManager.GetString("MsgDeletedItems2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на directory not found.
        /// </summary>
        public static string MsgDirectoryNotFound {
            get {
                return ResourceManager.GetString("MsgDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update download failed..
        /// </summary>
        public static string MsgDownloadFailed {
            get {
                return ResourceManager.GetString("MsgDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на archive is empty.
        /// </summary>
        public static string MsgEmptyArchive {
            get {
                return ResourceManager.GetString("MsgEmptyArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error extracting file.
        /// </summary>
        public static string MsgErrorExtracting {
            get {
                return ResourceManager.GetString("MsgErrorExtracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error opening file.
        /// </summary>
        public static string MsgErrorOpening {
            get {
                return ResourceManager.GetString("MsgErrorOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extracted {0} into {1}.
        /// </summary>
        public static string MsgExtractComplete {
            get {
                return ResourceManager.GetString("MsgExtractComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extracted {0} file.
        /// </summary>
        public static string MsgExtractedFiles1 {
            get {
                return ResourceManager.GetString("MsgExtractedFiles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extracted {0} files.
        /// </summary>
        public static string MsgExtractedFiles2 {
            get {
                return ResourceManager.GetString("MsgExtractedFiles2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extracting files from {0}.
        /// </summary>
        public static string MsgExtractingArchive {
            get {
                return ResourceManager.GetString("MsgExtractingArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extracting file from {0}.
        /// </summary>
        public static string MsgExtractingFile {
            get {
                return ResourceManager.GetString("MsgExtractingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extracting files from {0} to {1}.
        /// </summary>
        public static string MsgExtractingTo {
            get {
                return ResourceManager.GetString("MsgExtractingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} file.
        /// </summary>
        public static string MsgFiles1 {
            get {
                return ResourceManager.GetString("MsgFiles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} files.
        /// </summary>
        public static string MsgFiles2 {
            get {
                return ResourceManager.GetString("MsgFiles2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image {0} x {1} x {2}bpp [{3}].
        /// </summary>
        public static string MsgImageSize {
            get {
                return ResourceManager.GetString("MsgImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на no files to extract.
        /// </summary>
        public static string MsgNoFiles {
            get {
                return ResourceManager.GetString("MsgNoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No entries matching &quot;{0}&quot;.
        /// </summary>
        public static string MsgNoMatching {
            get {
                return ResourceManager.GetString("MsgNoMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No media files selected..
        /// </summary>
        public static string MsgNoMediaFiles {
            get {
                return ResourceManager.GetString("MsgNoMediaFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No updates currently available..
        /// </summary>
        public static string MsgNoUpdates {
            get {
                return ResourceManager.GetString("MsgNoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File {0}
        ///already exists.
        ///
        ///Overwrite?.
        /// </summary>
        public static string MsgOverwrite {
            get {
                return ResourceManager.GetString("MsgOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Playing {0} / {3} / {2}bps / {1}Hz.
        /// </summary>
        public static string MsgPlaying {
            get {
                return ResourceManager.GetString("MsgPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ready.
        /// </summary>
        public static string MsgReady {
            get {
                return ResourceManager.GetString("MsgReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} file added to selection.
        /// </summary>
        public static string MsgSelectedFiles1 {
            get {
                return ResourceManager.GetString("MsgSelectedFiles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} files added to selection.
        /// </summary>
        public static string MsgSelectedFiles2 {
            get {
                return ResourceManager.GetString("MsgSelectedFiles2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на unable to interpret audio format.
        /// </summary>
        public static string MsgUnableInterpretAudio {
            get {
                return ResourceManager.GetString("MsgUnableInterpretAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на unable to interpret image format.
        /// </summary>
        public static string MsgUnableInterpretImage {
            get {
                return ResourceManager.GetString("MsgUnableInterpretImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Formats database update available..
        /// </summary>
        public static string MsgUpdateAvailable {
            get {
                return ResourceManager.GetString("MsgUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Formats database updated..
        /// </summary>
        public static string MsgUpdateComplete {
            get {
                return ResourceManager.GetString("MsgUpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update check failed..
        /// </summary>
        public static string MsgUpdateFailed {
            get {
                return ResourceManager.GetString("MsgUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GARbro version is up to date..
        /// </summary>
        public static string MsgUpToDate {
            get {
                return ResourceManager.GetString("MsgUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version {0}.
        /// </summary>
        public static string MsgVersion {
            get {
                return ResourceManager.GetString("MsgVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Archives.
        /// </summary>
        public static string TextAboutArchives {
            get {
                return ResourceManager.GetString("TextAboutArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Audio.
        /// </summary>
        public static string TextAboutAudio {
            get {
                return ResourceManager.GetString("TextAboutAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [builtin].
        /// </summary>
        public static string TextAboutBuiltin {
            get {
                return ResourceManager.GetString("TextAboutBuiltin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Images.
        /// </summary>
        public static string TextAboutImages {
            get {
                return ResourceManager.GetString("TextAboutImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License.
        /// </summary>
        public static string TextAboutLicense {
            get {
                return ResourceManager.GetString("TextAboutLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About Game Resource browser.
        /// </summary>
        public static string TextAboutTitle {
            get {
                return ResourceManager.GetString("TextAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All Files.
        /// </summary>
        public static string TextAllFiles {
            get {
                return ResourceManager.GetString("TextAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на as is.
        /// </summary>
        public static string TextAsIs {
            get {
                return ResourceManager.GetString("TextAsIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Audio will be converted to either WAV, MP3 or OGG..
        /// </summary>
        public static string TextAudioConversion {
            get {
                return ResourceManager.GetString("TextAudioConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose archive location.
        /// </summary>
        public static string TextChooseArchive {
            get {
                return ResourceManager.GetString("TextChooseArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose destination directory.
        /// </summary>
        public static string TextChooseDestDir {
            get {
                return ResourceManager.GetString("TextChooseDestDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm overwrite.
        /// </summary>
        public static string TextConfirmOverwrite {
            get {
                return ResourceManager.GetString("TextConfirmOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert audio to common format.
        /// </summary>
        public static string TextConvertAudio {
            get {
                return ResourceManager.GetString("TextConvertAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Media conversion.
        /// </summary>
        public static string TextConvertMedia {
            get {
                return ResourceManager.GetString("TextConvertMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create archive.
        /// </summary>
        public static string TextCreateArchive {
            get {
                return ResourceManager.GetString("TextCreateArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Archive creation error.
        /// </summary>
        public static string TextCreateArchiveError {
            get {
                return ResourceManager.GetString("TextCreateArchiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete files.
        /// </summary>
        public static string TextDeleteFiles {
            get {
                return ResourceManager.GetString("TextDeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text encoding.
        /// </summary>
        public static string TextEncoding {
            get {
                return ResourceManager.GetString("TextEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error occured while converting file
        ///{0}
        ///{1}.
        /// </summary>
        public static string TextErrorConverting {
            get {
                return ResourceManager.GetString("TextErrorConverting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error occured while extracting file
        ///{0}
        ///{1}.
        /// </summary>
        public static string TextErrorExtracting {
            get {
                return ResourceManager.GetString("TextErrorExtracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extract audio.
        /// </summary>
        public static string TextExtractAudio {
            get {
                return ResourceManager.GetString("TextExtractAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extract images.
        /// </summary>
        public static string TextExtractImages {
            get {
                return ResourceManager.GetString("TextExtractImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File extraction error.
        /// </summary>
        public static string TextExtractionError {
            get {
                return ResourceManager.GetString("TextExtractionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extract text.
        /// </summary>
        public static string TextExtractText {
            get {
                return ResourceManager.GetString("TextExtractText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extract from archive.
        /// </summary>
        public static string TextExtractTitle {
            get {
                return ResourceManager.GetString("TextExtractTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File {0} already exists in the destination folder..
        /// </summary>
        public static string TextFileAlreadyExists {
            get {
                return ResourceManager.GetString("TextFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Formats.
        /// </summary>
        public static string TextFormats {
            get {
                return ResourceManager.GetString("TextFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Multimedia conversion error.
        /// </summary>
        public static string TextMediaConvertError {
            get {
                return ResourceManager.GetString("TextMediaConvertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New version available:.
        /// </summary>
        public static string TextNewVersion {
            get {
                return ResourceManager.GetString("TextNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Archive parameters.
        /// </summary>
        public static string TextParametersTitle {
            get {
                return ResourceManager.GetString("TextParametersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preferences.
        /// </summary>
        public static string TextPreferences {
            get {
                return ResourceManager.GetString("TextPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save as.
        /// </summary>
        public static string TextSaveAs {
            get {
                return ResourceManager.GetString("TextSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save images as.
        /// </summary>
        public static string TextSaveImagesAs {
            get {
                return ResourceManager.GetString("TextSaveImagesAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select files.
        /// </summary>
        public static string TextSelectFiles {
            get {
                return ResourceManager.GetString("TextSelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Game Resource browser.
        /// </summary>
        public static string TextTitle {
            get {
                return ResourceManager.GetString("TextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application update.
        /// </summary>
        public static string TextUpdateTitle {
            get {
                return ResourceManager.GetString("TextUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image viewer.
        /// </summary>
        public static string TextViewer {
            get {
                return ResourceManager.GetString("TextViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Visit download page.
        /// </summary>
        public static string TextVisitPage {
            get {
                return ResourceManager.GetString("TextVisitPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Either WAV, MP3 or OGG.
        /// </summary>
        public static string TooltipAudioFormats {
            get {
                return ResourceManager.GetString("TooltipAudioFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        public static string TooltipBack {
            get {
                return ResourceManager.GetString("TooltipBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Forward.
        /// </summary>
        public static string TooltipForward {
            get {
                return ResourceManager.GetString("TooltipForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;DIR&gt;.
        /// </summary>
        public static string Type_directory {
            get {
                return ResourceManager.GetString("Type_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на none.
        /// </summary>
        public static string Type_NONE {
            get {
                return ResourceManager.GetString("Type_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scale large images to fit window.
        /// </summary>
        public static string winDownScaleImage {
            get {
                return ResourceManager.GetString("winDownScaleImage", resourceCulture);
            }
        }
    }
}
