<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>GameRes.Legacy</RootNamespace>
    <AssemblyName>ArcLegacy</AssemblyName>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Configurations>Debug;Prerelease;Release</Configurations>
    <PreBuildEvent>perl "$(SolutionDir)inc-revision.pl" "$(ProjectPath)" $(ConfigurationName)
exit 0</PreBuildEvent>
    <AssemblyTitle>Legacy</AssemblyTitle>
    <Description>Outdated resource formats</Description>
    <Company>mørkt</Company>
    <Product>Legacy</Product>
    <Copyright>Copyright © 2017-2018 mørkt</Copyright>
    <AssemblyVersion>1.0.10.212</AssemblyVersion>
    <FileVersion>1.0.10.212</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\bin\Debug\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\bin\Release\</OutputPath>
    <DefineConstants>
    </DefineConstants>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Prerelease|AnyCPU'">
    <OutputPath>bin\Prerelease\</OutputPath>
    <Optimize>true</Optimize>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <!-- <Compile Include="Nanami\ArcBMM.cs" /> -->
    <None Include="PlanTech\ImagePAC.cs" />
    <PackageReference Include="System.ComponentModel.Composition" Version="10.0.10" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="SharpZipLib" Version="1.3.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ArcFormats\ArcFormats.csproj" />
    <ProjectReference Include="..\GameRes\GameRes.csproj" />
  </ItemGroup>
</Project>